[project]
name = "yaitec-hub-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.9.2",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.2",
]
